version: '3'
services:
  opentsdb:
    image: quay.io/kaszpir/opentsdb:2.4.0
    environment:
    - ZKQUORUM=zookeeper:2181
    - ZKBASEDIR=/hbase
    - TSDB_OPTS="--read-only"
    - TSDB_PORT=4242
  zookeeper:
    image: zookeeper:3.4
